language: java
sudo: true
jdk:
  - oraclejdk17
before_install:
  - chmod +x mvnw
  - curl -sL https://github.com/jpm4j/jpm4j.installers/blob/master/dist/biz.aQute.jpm.run.jar?raw=true > jpm4j.jar
  - sudo java -jar jpm4j.jar -g init
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
install:
  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml  --p
cache:
  directories:
    - "$HOME/.m2/repository"